// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDx-XMCWZsx53r1Ux7wzNxqr7zbmeKyTHw',
    appId: '1:131226420477:web:f4717fb093c269ad13aa94',
    messagingSenderId: '131226420477',
    projectId: 'reminders-c8bd8',
    authDomain: 'reminders-c8bd8.firebaseapp.com',
    storageBucket: 'reminders-c8bd8.firebasestorage.app',
    measurementId: 'G-6C6CJRY17Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGU9l8WX-waiXDj5fB4pcz5w6N8lSQJTc',
    appId: '1:131226420477:android:a4d1705fbb5b504513aa94',
    messagingSenderId: '131226420477',
    projectId: 'reminders-c8bd8',
    storageBucket: 'reminders-c8bd8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaMwAhBhg9tXVMBmp8PdlsDQ5CWqfCttc',
    appId: '1:131226420477:ios:da82e4fa77ef551c13aa94',
    messagingSenderId: '131226420477',
    projectId: 'reminders-c8bd8',
    storageBucket: 'reminders-c8bd8.firebasestorage.app',
    iosBundleId: 'com.example.reminderApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaMwAhBhg9tXVMBmp8PdlsDQ5CWqfCttc',
    appId: '1:131226420477:ios:da82e4fa77ef551c13aa94',
    messagingSenderId: '131226420477',
    projectId: 'reminders-c8bd8',
    storageBucket: 'reminders-c8bd8.firebasestorage.app',
    iosBundleId: 'com.example.reminderApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDx-XMCWZsx53r1Ux7wzNxqr7zbmeKyTHw',
    appId: '1:131226420477:web:81db36e3e288409213aa94',
    messagingSenderId: '131226420477',
    projectId: 'reminders-c8bd8',
    authDomain: 'reminders-c8bd8.firebaseapp.com',
    storageBucket: 'reminders-c8bd8.firebasestorage.app',
    measurementId: 'G-MGS255XGPB',
  );
}
