name: Deploy to FTP

on:
  push:
    branches:
      - main # Or your default branch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Flutter web app
        run: flutter build web --base-href /reminders/
        working-directory: ./reminder_app

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./reminder_app/build/web/
          server-dir: /public_html/reminders/
